name: タグを付与してリリースすると、イメージを作成する

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for PHP container
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-php

      - name: Build and push Docker PHP with App image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: php
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Extract metadata (tags, labels) for NGINX container
        id: meta2
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-nginx

      - name: Build and push Docker NGINX image
        id: push2
        uses: docker/build-push-action@v5
        with:
          context: nginx
          push: true
          tags: ${{ steps.meta2.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta2.outputs.labels }}

